server:
  servlet:
    #项目发布路径
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    #编辑Mybatis配置
mybatis:
  #定义别名包
  type-aliases-package: com.jt.springboot.pojo
  #加载mapper映射文件
  mapper-locations: classpath:/mybatis/mapper/*Mapper.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.jt.springboot.dao: debug